In [1]:
#Were gonna go over the undamentals

Introduction to Tensors

In [2]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.5.0


In [3]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar


2021-07-10 19:42:43.381309: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check the number of dimension of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#Check the dimension of our vector
vector.ndim

1

In [7]:
#Create a matric (Has more than one dimension)
matrix = tf.constant([[10,7],
                      [1,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#Create another matrix
another_matrix = tf.constant([[7.,3],
                               [12.,4.],
                               [9.,8.]], dtype=tf.float16) # specify the data type with dtype parameters
another_matrix                  

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7.,  3.],
       [12.,  4.],
       [ 9.,  8.]], dtype=float16)>

In [10]:
#Dimensions of another_matrix
another_matrix.ndim

2

In [11]:
#Lets creat a tensor!
tensor = tf.constant([[[1,2,3],
                     [4,5,6],],
                      
                     [[7,8,9],
                      [10,11,12]],
                      
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

#What we've created so far
#- Scalar: A single number
#-Vector: a number with direction(eg. windspeed and direction)
#- Matrix: a 2-dimensional array
#- Tensor: an n-dimensional array of numbers(when n can be any number, a 0 dimensional tensor is scalar, a 1-dimensional tensor is a vector.)

In [13]:
#Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#Let's try change one of the elements in our changeable tensor
#changeable_tensor[0] = 7
#changeable_tensor

In [15]:
#Lets try assign instead .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
#Trying to change the unchangeable
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

**Creating random tensors**



---
Random tensors are tensors of some arbitrary size which contain random numbers.





In [17]:
#Creating 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) #random seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
#Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#Shuffle the order of elements in a tensor

In [18]:
#Shuffle a tensor (Valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
#shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
#**Exercise**
#Set moth seeds to random in order to get same results

In [21]:
#Other ways to make tensors

tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [22]:
#Turn Numpy Arrays into Tensors
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32) #Create a array between one and 25
numpy_A 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A, shape =(4,6))
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [24]:
#Getting info from tensors
#* Shape
#* Rank
#* Axis or dimension
#* Size


In [25]:
#Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
2*3*4*5

120

In [28]:
#Get various attibutes of our tensor
print("Datatype of every element:" , rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements of elemnts in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements of elemnts in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements of elemnts in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements of elemnts in our tensor: 120


In [29]:
 ###Indexing Tensors
 #Tensors can be indexed just like Python Lists.

In [30]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [31]:
 #Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
#Get the first dimension of each index except for the final one
rank_4_tensor[:1,:1,:1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
#Create a rank 2 tensor (2dimensions)
rank_2_tensor = tf.constant([[5,4],
                             [6,7]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 4],
       [6, 7]], dtype=int32)>

In [34]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [35]:
#Get the last item of each row of our rank 2 tensor

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 7], dtype=int32)>

In [36]:
#add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [4]],

       [[6],
        [7]]], dtype=int32)>

In [37]:
#Alternative to new axis
tf.expand_dims(rank_2_tensor,axis = -1 ) # "-1" means to expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [4]],

       [[6],
        [7]]], dtype=int32)>

In [38]:
tf.expand_dims(rank_2_tensor,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 4],
        [6, 7]]], dtype=int32)>

In [39]:
###Manipulating Tensor (Tensor Operations)
#basic Operations

# +, -, *, /

In [40]:
#You can add value to a tensor using the addition operator
tensor = rank_2_tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 4],
       [6, 7]], dtype=int32)>

In [41]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 14],
       [16, 17]], dtype=int32)>

In [42]:
#Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 40],
       [60, 70]], dtype=int32)>

In [43]:
#Subtraction 
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-5, -6],
       [-4, -3]], dtype=int32)>

In [44]:
#We can use the tensorflow
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 40],
       [60, 70]], dtype=int32)>


##Matric Multiplication
#In machine learning Matrix multiplication is one of the most common tensor operations
```
# This is formatted as code
```



In [45]:
print(rank_2_tensor)
tf.matmul(rank_2_tensor, rank_2_tensor)

tf.Tensor(
[[5 4]
 [6 7]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[49, 48],
       [72, 73]], dtype=int32)>

In [46]:
rank_2_tensor * rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 16],
       [36, 49]], dtype=int32)>

In [47]:
exer3 = tf.constant([[1,2,5],
                     [7,2,1],
                     [3,3,3]])
exer3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [48]:
exer2by3 = tf.constant([[3,5],
                     [6,7],
                     [1,8]])
exer2by3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [49]:
tf.matmul(exer3, exer2by3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [50]:
#Matrix Multiplication with Python
exer3 @ exer2by3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [51]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8,9],
                 [10,11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [52]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [53]:
tf.reshape(X, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [54]:
Y @ tf.reshape(X, shape=(3,2))


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136]], dtype=int32)>

In [55]:
  #Can do the same with transpose
X,  tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [56]:
#Try matrix multiplication with transpose rather than reshape
#tf.matmul(tf.transpose(X), Y)

In [57]:
#@title The dot product
#@markdown MAtrix multiplication is also referred to as the dot product.

#@markdown You can preform matrix multiplication using

#@markdown - tf.matmul
#@markdown - tf.tensordot




In [58]:
Y = tf.reshape(Y, shape=(3,2))

In [59]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [60]:
#Perform matrix multiplication between X and Y (transposed)

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [61]:
#Check values of Y and transpose Y
print("Normal Y:")
print(Y, "\n") # "\n" is for newline

print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)), "\n" )

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [62]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [63]:
#@markdown Generally when performing matrix multiplication onto the tensors and one of the axes doesnt line up you will transpose (rather then reshape) one of the tensors to satisfy the matrix multiplication rules.

In [64]:
#@title Changing the datatypes of a tensor

In [65]:
#Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [66]:
C = tf.constant([7,10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [67]:
tf.__version__

'2.5.0'

In [68]:
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [69]:
#Change from int32 to float 32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [70]:
#@markdown Aggregating tensors

In [71]:
D = tf.constant ([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [72]:
#Get absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [73]:
#@markdown Lets go through the following forms of aggregation
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

In [74]:
aggie1 = tf.constant([[-33,4],
                     [55,12],
                     [-19,3]])

In [75]:
#Minimum
tf.reduce_min(aggie1)

<tf.Tensor: shape=(), dtype=int32, numpy=-33>

In [76]:
#Maximum
tf.reduce_max(aggie1)

<tf.Tensor: shape=(), dtype=int32, numpy=55>

In [77]:
#Mean
tf.reduce_mean(aggie1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [78]:
#SUM
tf.reduce_sum(aggie1)

<tf.Tensor: shape=(), dtype=int32, numpy=22>

In [79]:
#Randomtensor Example
randomT = tf.constant(np.random.randint(0,100, size=50))
randomT

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([83, 13,  4, 78, 40,  8, 39, 40, 81,  7, 81, 10, 79, 40, 20, 81, 55,
       33, 76, 79, 92,  4,  0,  6, 28, 25,  2, 21, 54, 36, 75, 14, 60, 98,
       23, 45, 52, 92, 95, 64, 11, 57, 22, 33, 12, 30, 85, 96, 80, 86])>

In [80]:
tf.size(randomT), randomT.shape, randomT.ndim 

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [81]:
#Minimum
tf.reduce_min(randomT)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [82]:
#Maximum
tf.reduce_max(randomT)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [83]:
#Mean
tf.reduce_mean(randomT)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [84]:
#SUM
tf.reduce_sum(randomT)

<tf.Tensor: shape=(), dtype=int64, numpy=2345>

In [85]:
#*EXERCISE* Find variance and standard deviation of randomT
randomS = tf.cast(randomT, dtype=tf.float32)
randomS

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([83., 13.,  4., 78., 40.,  8., 39., 40., 81.,  7., 81., 10., 79.,
       40., 20., 81., 55., 33., 76., 79., 92.,  4.,  0.,  6., 28., 25.,
        2., 21., 54., 36., 75., 14., 60., 98., 23., 45., 52., 92., 95.,
       64., 11., 57., 22., 33., 12., 30., 85., 96., 80., 86.],
      dtype=float32)>

In [86]:
#Variance
tf.math.reduce_variance(randomS)

<tf.Tensor: shape=(), dtype=float32, numpy=976.81>

In [87]:
#Standard deviation
tf.math.reduce_std(randomS)

<tf.Tensor: shape=(), dtype=float32, numpy=31.25396>

In [88]:
#@title FInd the positional minimum and Max
#MAX
tf.argmax(randomS)

<tf.Tensor: shape=(), dtype=int64, numpy=33>

In [89]:
#MIN
tf.argmin(randomS)

<tf.Tensor: shape=(), dtype=int64, numpy=22>

In [90]:
tf.__version__

'2.5.0'

In [91]:
########Find positional Max and MIN

#Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [92]:
#Find positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [93]:
#Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [94]:
#Find the max value orf F

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [95]:
#Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [96]:
#Find positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [97]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [98]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [99]:
#Squeezing a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [100]:
G.shape


TensorShape([1, 1, 1, 1, 50])

In [101]:
G_squeezed = tf.squeeze(G)
G_squeezed, G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [102]:
G_squeezed.shape

TensorShape([50])

In [103]:
#Create list of indices

some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [104]:
#Spcify custom values for one hot encoding

tf.one_hot(some_list,depth = 4, on_value = 7, off_value = 0 )

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[7, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 7]], dtype=int32)>

In [105]:
###Squaring, log and squareRoot

In [106]:
#Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [107]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [108]:
#MUST TURN INTO FLOAT
#Find sqrt

tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [109]:
#MUST TURN INTO FLOAT
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [110]:
###TENSORS AND NUMPY

In [111]:
#Tensorflow interacts beautifully with numpy arrays

#Create a tensor directly from a Numpy array

J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [112]:
#Convert our tensor back to a numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [113]:
#Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [114]:
#Default types of each are slightly different

In [115]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
#Check the datatypes of each
numpy_J.dtype, tensor_J

(tf.float64,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 3.,  7., 10.], dtype=float32)>)

In [116]:
#Finding access to GPU's

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]