In [6]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.5.0'

In [5]:
vec = tf.constant([1])
vec
sca = tf.constant([[1,2],
                   [3,4]])
sca
mat = tf.constant([[1,2,3],
                   [3,4,5],
                   [6,7,8]])
mat

tenso = tf.random.Generator.from_seed(7)
tenso = tenso.normal(shape=(4,2))

vec, sca, mat, tenso

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707],
        [-0.06378496,  0.92800784]], dtype=float32)>)

In [9]:
randten = tf.random.uniform(shape=(5,100), minval=0, maxval=1)
randten

<tf.Tensor: shape=(5, 100), dtype=float32, numpy=
array([[0.69810593, 0.24328542, 0.9302224 , 0.4682274 , 0.10837996,
        0.46103883, 0.6794839 , 0.85993683, 0.02834177, 0.9837601 ,
        0.3972329 , 0.64405036, 0.04081964, 0.45963812, 0.5771872 ,
        0.6043031 , 0.8865248 , 0.01725161, 0.18249452, 0.34137976,
        0.8536484 , 0.7692814 , 0.21185231, 0.4986645 , 0.39222503,
        0.9023471 , 0.82929564, 0.07393169, 0.14325595, 0.6918906 ,
        0.3077743 , 0.23948789, 0.8981546 , 0.7003335 , 0.82735145,
        0.6627928 , 0.22725594, 0.4914899 , 0.05494153, 0.7518021 ,
        0.9044193 , 0.8168876 , 0.62230825, 0.8367456 , 0.28360498,
        0.06724119, 0.78119123, 0.45798242, 0.1941756 , 0.47936916,
        0.09622252, 0.875407  , 0.34820282, 0.26665854, 0.6842706 ,
        0.07010949, 0.7656449 , 0.73398054, 0.2161485 , 0.5232183 ,
        0.884058  , 0.05149996, 0.5361707 , 0.14862871, 0.3133117 ,
        0.96454513, 0.0625912 , 0.01231551, 0.9787642 , 0.200701  

In [10]:
print("Datatype of every element:" , randten.dtype)
print("Number of dimensions (rank): ", randten.ndim)
print("Shape of tensor:", randten.shape)
print("Elements along the 0 axis:", randten.shape[0])
print("Elements along the last axis:", randten.shape[-1])
print("Total number of elements of elemnts in our tensor:", tf.size(randten))
print("Total number of elements of elemnts in our tensor:", tf.size(randten).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank):  2
Shape of tensor: (5, 100)
Elements along the 0 axis: 5
Elements along the last axis: 100
Total number of elements of elemnts in our tensor: tf.Tensor(500, shape=(), dtype=int32)
Total number of elements of elemnts in our tensor: 500


In [8]:
tf.matmul(tenso, randten)

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 5: [4,2] [5,100] 0 0 [Op:MatMul]